FROM php:5.6.24-fpm

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests  -y \
        libpng12-dev \
        libxml2-dev \
        libldap2-dev \
        libldb-dev \
        unzip \
        php5-mysql \
        libzip-dev \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
    && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so \
    && docker-php-ext-install -j$(nproc) xml gd ldap mysql \
    && pecl install timezonedb \
    && docker-php-ext-enable timezonedb \
    && curl https://getcomposer.org/download/1.2.0/composer.phar -o /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && ln -s /etc/php5/mods-available/pdo_mysql.ini /usr/local/etc/php/conf.d/pdo_mysql.ini \
    && ln -s /usr/lib/php5/20131226/pdo.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo.so \
    && ln -s /usr/lib/php5/20131226/pdo_mysql.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so \
    && pecl install -f oauth-1.2.3 \
    && pecl install -f zip

COPY docker/php.ini /usr/local/etc/php/
COPY . /var/www/html

RUN cd /var/www/html \
    && composer install \
    && mkdir -p /var/www/html/app/tmp/cache/persistent /var/www/html/app/tmp/cache/models \
    && chown www-data:www-data -R /var/www/html/app/tmp/cache

RUN echo "extension=oauth.so" >> /usr/local/etc/php/php.ini
RUN echo "extension=zip.so" >> /usr/local/etc/php/php.ini