FROM php:7.4-fpm

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests  -y \
        libpng-dev \
        libxml2-dev \
        libldap2-dev \
        libldb-dev \
        unzip \
        git \
        libpcre3-dev \
        libzip-dev \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
    && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so \
    && docker-php-ext-install -j$(nproc) xml gd ldap mysqli pdo_mysql intl zip \
    && pecl install timezonedb \
    && docker-php-ext-enable timezonedb \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && pecl install -f oauth-2.0.7

COPY docker/php.ini /usr/local/etc/php/
COPY . /var/www/html

COPY --from=composer:2.4 /usr/bin/composer /usr/local/bin/composer

RUN cd /var/www/html \
    && composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-suggest --optimize-autoloader \
    && mkdir -p /var/www/html/app/tmp/cache/persistent /var/www/html/app/tmp/cache/models \
    && chown www-data:www-data -R /var/www/html/app/tmp/cache

RUN echo "extension=oauth.so" >> /usr/local/etc/php/php.ini
RUN echo "extension=zip.so" >> /usr/local/etc/php/php.ini
RUN echo "opcache.enable=0" >> /usr/local/etc/php/php.ini
